//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desenvolvimento_Web_2___Rodrigo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO
    {
        public int Id { get; set; }
        public string Descricao { get; set; }
        public decimal Valor { get; set; }
        public int CategoriaId { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
    }
}
